import SEOWrapper from '../components/SEO/SEOWrapper';

const AI_NOTICE =
  'Outputs generated by AI workflows may contain errors or bias and must be reviewed by a qualified human before acting.';

export default function AIDisclosurePage() {
  return (
    <>
      <SEOWrapper
        title="AI Use & Disclosures | Build Media Strategies"
        description="Learn how Build Media Strategies deploys AI responsibly, what data is logged, and how we maintain human oversight."
        canonical="https://buildmediastrategies.com/ai-disclosure"
      />
      <main className="bg-white py-16 px-6">
        <div className="max-w-4xl mx-auto space-y-6 text-black">
          <h1 className="text-4xl font-bold text-sky-gradient">AI Use & Disclosures</h1>
          <p>
            We rely on a mix of proprietary automations and third-party large language models to draft copy, analyse performance
            data, and streamline operations. Whenever an experience involves AI we clearly label it so you know the content may
            have been generated or assisted by a machine.
          </p>
          <p>
            Prompts, outputs, and system decisions may be logged to help us audit activity, detect abuse, and improve the
            reliability of our workflows. These logs are encrypted, access controlled, and deleted on a rolling schedule unless
            we are required to preserve them for contractual or regulatory reasons.
          </p>
          <p aria-label={AI_NOTICE}>
            AI outputs can include inaccuracies or bias. We recommend a qualified human reviews any recommendations before they
            are shared publicly or used to make important decisions. Enterprise deployments include escalation paths so you can
            request manual review or opt out of automated actions entirely.
          </p>
          <p>
            Sensitive or personal information is only processed inside private environments that meet our internal security
            checklist. We regularly stress-test prompts, apply policy filters, and ensure that data provided by one client is
            never used to train another client&apos;s model without explicit permission.
          </p>
          <p>
            If you have questions about how AI is used in your specific engagement, contact hello@buildmediastrategies.com and a
            member of our team will provide a detailed explanation of the safeguards in place.
          </p>
        </div>
      </main>
    </>
  );
}
